name: arXiv Daily Papers

on:
  schedule:
    - cron: '40 3 * * *'  # 每天 UTC+8 时间 11:40 运行
  # 允许手动触发
  workflow_dispatch:
    inputs:
      # 定义可选的输入参数
      message:
        description: 'Optional message for the run'
        required: false
        default: 'Manual run'

jobs:
  get-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Get daily papers
        run: python run.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update daily papers"
            git push
          fi
